/* DO NOT EDIT THIS FILE - it is machine generated */
#include <jni.h>
/* Header for class net_techcable_accelerated_java_jni_ZLibNative */

#ifndef _Included_net_techcable_accelerated_java_jni_ZLibNative
#define _Included_net_techcable_accelerated_java_jni_ZLibNative
#ifdef __cplusplus
extern "C" {
#endif

#define DEFLATE_TYPE_ID 0
#define INFLATE_TYPE_ID 1

JNIEXPORT jlong JNICALL Java_net_techcable_accelerated_1java_jni_ZLibNative_createStream0(JNIEnv *, jclass, jint, jint);

JNIEXPORT jint JNICALL Java_net_techcable_accelerated_1java_jni_ZLibNative_inflate0(JNIEnv *, jclass, jlong, jlong, jlong, jint, jlong, jint);

JNIEXPORT jint JNICALL Java_net_techcable_accelerated_1java_jni_ZLibNative_deflate0(JNIEnv *, jclass, jlong, jlong, jlong, jint, jlong, jint, jboolean);

JNIEXPORT void JNICALL Java_net_techcable_accelerated_1java_jni_ZLibNative_free0(JNIEnv *, jclass, jlong, jint typeId);

#ifdef __cplusplus
}
#endif
#endif
